version: '3'
services:
  my-container-1:
    container_name: voicevox-cpu-latest
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - 50021:50021
    networks:
      mynetwork:
        ipv4_address: 172.81.0.3

networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.81.0.0/16